# -*- coding: utf-8 -*-
"""Tsunami.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SBMK2jBghvQjqVfr5eRN38l_o2CZg_z7
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
le = LabelEncoder()
# %matplotlib inline

data1 = pd.read_csv('earthquake_data.csv')
data1 = data1.drop(columns=["title","date_time","location","country","continent"])
#
le = LabelEncoder()
data1.alert = le.fit_transform(data1.alert)
data1.net = le.fit_transform(data1.net)
data1.magType = le.fit_transform(data1.magType)
data1 = data1.fillna(0)
x3 = data1.drop(columns=["tsunami"])
y3 = data1["tsunami"]
data1.head()

sns.heatmap(data1.corr())

x_train, x_test, y_train, y_test = train_test_split(x3,y3,test_size=0.2)
md = tree.DecisionTreeClassifier()
md.fit(x_train,y_train)
md.score(x_test,y_test)

md = RandomForestClassifier()
md.fit(x_train,y_train)
md.score(x_test,y_test)

import joblib
joblib.dump(md,'Model4')
print("Training and testing complete" )


